### ISSUE TITLE
Investigate and Document FleetShard Operator Patterns

### ISSUE THREAD

**Issue by davidffrench** [bf2fc6cc711aee1a0c2a/ffm-project#14]
### Description
Based on a discussion in [Zulip](https://bf2.zulipchat.com/#narrow/stream/315461-factorized-fleet-manager/topic/Fleetshard.20Operator.20and.20Synchronizer), there are numerous patterns in use for the RHOSAK fleetshard operator which would be useful for other managed services teams looking to build their own.

Some examples:
- Cluster status reporting (readiness, capacity, utilisation) to the fleet manager
- Reporting service instance status

It is likely this information is captured in ADRs and other documents, ideally this would be made available as links or direct documentation in [ffm-fleet-manager-go-template](https://github.com/bf2fc6cc711aee1a0c2a/ffm-fleet-manager-go-template), for now at least. If in the future, there is a separate fleetshard template or SDK, it could be moved at that time.

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

**Comment by machi1990** [comment]
I'll be looking at this

**Comment by davidffrench** [comment]
Thanks Manyanda

**Comment by machi1990** [comment]
Closed by https://github.com/bf2fc6cc711aee1a0c2a/ffm-fleet-manager-go-template/pull/22
