### ISSUE TITLE
Zullip link on communication page is incorrect

### ISSUE THREAD

**Issue by balunasj** [bf2fc6cc711aee1a0c2a/ffm-project#18]
Zullip link on communication page for project incorrect:

https://github.com/bf2fc6cc711aee1a0c2a/ffm-project/wiki/How-to-communicate-in-the-project

It's https://bf2/zulipchat.com not https://bf2.zulipchat.com

**Comment by machi1990** [comment]
Thanks @balunasj for spotting it. I've updated the link.
